=== sherbold/CrossPare/CrossPare/experimentconfig.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="experimentconfig"
    elementFormDefault="qualified"
    xmlns="experimentconfig"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:element name="config">
    <xs:complexType>
      <xs:sequence minOccurs="1" maxOccurs="1">
        <xs:element name="partialconfig" type="pathType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="loader" type="datapathType" minOccurs="0" maxOccurs="unbounded"/>
		<xs:element name="executionStrategy" type="xs:string" minOccurs="0" maxOccurs="1"/>
		<xs:element name="saveClassifier" type="xs:string" minOccurs="0" maxOccurs="1" />
        <xs:element name="resultspath" type="pathType" minOccurs="0" maxOccurs="1"/>
        <xs:element name="versionfilter" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="testVersionfilter" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="trainVersionfilter" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="setwisepreprocessor" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="setwiseselector" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="setwisepostprocessor" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="setwisetrainer" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="setwisetestdataawaretrainer" type="metricMatchingType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="preprocessor" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="pointwiseselector" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="postprocessor" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="trainer" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="testawaretrainer" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="eval" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="storage" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="repetitions" type="repetitionsType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="datapathType">
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="datalocation" type="xs:string" />
    <xs:attribute name="relative" type="xs:boolean" default="true"/>
  </xs:complexType>
  <xs:complexType name="pathType">
    <xs:attribute name="path" type="xs:string" />
    <xs:attribute name="relative" type="xs:boolean" default="true"/>
  </xs:complexType>
  <xs:complexType name="setupType">
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="param" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="metricMatchingType">
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="param" type="xs:string" />
    <xs:attribute name="method" type="xs:string" />
    <xs:attribute name="threshold" type="xs:float" />
  </xs:complexType>
  <xs:complexType name="repetitionsType">
  	<xs:attribute name="number" type="xs:integer" />
  </xs:complexType>
</xs:schema>

=== sherbold/CrossPare/CrossPare/testdata/metrics_vs_costsaving/generalization/MYNBOU_3_Peters15.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="experimentconfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="experimentconfig experimentconfig.xsd">
    <loader name="MynbouFolderLoader" datalocation="testdata/mynbou" param="SM_file.* SM_class.*_sum" relative="false" classtype="numeric"/>
    <executionStrategy name="WithinProjectPreviousReleasesExperiment" param="1" />
    <trainVersionfilter name="MinInstanceNumberFilter" param="100" />
    <trainVersionfilter name="MinClassNumberFilter" param="5" />
    <trainVersionProcessor name="BugDateFilter" />
    <setwisepreprocessor name="MakeClassBinary" param="" />
    <setwisepreprocessor name="LogarithmTransform" param="" />
    <setwiseselector name="LACE2" param="0.4" />
    <pointwiseselector name="TurhanFilter" param="1" />
    <trainer name="WekaTraining" param="NB weka.classifiers.bayes.NaiveBayes" />
    <eval name="NormalWekaEvaluation" param="" />
    <storage name="MySQLResultStorage" param="" />
</config>

=== sherbold/CrossPare/CrossPare/testdata/configurations/JURECZKO-Turhan09.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="experimentconfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="experimentconfig experimentconfig.xsd">
 <loader name="CSVFolderLoader" datalocation="benchmark/data/JURECZKO" relative="false"/>
 <versionfilter name="MinClassNumberFilter" param="5" />
 <resultspath path="benchmark/results-csv"/>
 <trainer name="WekaTraining" param="NB weka.classifiers.bayes.NaiveBayes" />
 <trainer name="WekaTraining" param="RF weka.classifiers.trees.RandomForest -CVPARAM I 5 25 5" />
 <trainer name="WekaTraining" param="DT weka.classifiers.trees.J48 -CVPARAM C 0.1 0.3 5" />
 <trainer name="WekaTraining" param="LR weka.classifiers.functions.Logistic" />
 <trainer name="WekaTraining" param="NET weka.classifiers.functions.RBFNetwork -CVPARAM W 0.1 10.0 3.0 L 2.0 18.0 3.0" />
 <trainer name="WekaTraining" param="SVM weka.classifiers.functions.SMO -K weka.classifiers.functions.supportVector.RBFKernel" />
 <preprocessor name="LogarithmTransform" param="" />
 <pointwiseselector name="TurhanFilter" param="10" />
 <eval name="NormalWekaEvaluation" param="" />
 <storage name="MySQLResultStorage" param="" />
</config>
